/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as DashboardSurveyIdRouteImport } from './routes/dashboard.survey.$id'
import { Route as DashboardResponsesIdRouteImport } from './routes/dashboard.responses.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSurveyIdRoute = DashboardSurveyIdRouteImport.update({
  id: '/survey/$id',
  path: '/survey/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResponsesIdRoute = DashboardResponsesIdRouteImport.update({
  id: '/responses/$id',
  path: '/responses/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/s/$id': typeof SIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/responses/$id': typeof DashboardResponsesIdRoute
  '/dashboard/survey/$id': typeof DashboardSurveyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$id': typeof SIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/responses/$id': typeof DashboardResponsesIdRoute
  '/dashboard/survey/$id': typeof DashboardSurveyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/s/$id': typeof SIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/responses/$id': typeof DashboardResponsesIdRoute
  '/dashboard/survey/$id': typeof DashboardSurveyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/s/$id'
    | '/dashboard/'
    | '/dashboard/responses/$id'
    | '/dashboard/survey/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/s/$id'
    | '/dashboard'
    | '/dashboard/responses/$id'
    | '/dashboard/survey/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/s/$id'
    | '/dashboard/'
    | '/dashboard/responses/$id'
    | '/dashboard/survey/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/survey/$id': {
      id: '/dashboard/survey/$id'
      path: '/survey/$id'
      fullPath: '/dashboard/survey/$id'
      preLoaderRoute: typeof DashboardSurveyIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/responses/$id': {
      id: '/dashboard/responses/$id'
      path: '/responses/$id'
      fullPath: '/dashboard/responses/$id'
      preLoaderRoute: typeof DashboardResponsesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardResponsesIdRoute: typeof DashboardResponsesIdRoute
  DashboardSurveyIdRoute: typeof DashboardSurveyIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardResponsesIdRoute: DashboardResponsesIdRoute,
  DashboardSurveyIdRoute: DashboardSurveyIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
